### ISSUE TITLE
Error on file "fwtb.desktop": No such file or directory

### ISSUE THREAD

**Issue by Serial-Comma** [taotien/framework_toolbox#1]
I copy pasted the code for the installation. The first one worked fine, but even after adding .cargo/bin to my PATH, it still results in the error `Error on file "fwtb.desktop": No such file or directory`.

**Comment by taotien** [comment]
You'll want to run that command inside the directory where fwtb.desktop is downloaded, you can get it from the repo.

You'll also have to make sure the PATH you added cargo to is for your desktop environment, not just shell. For example, on KDE it's sourced from `~/.config/plasma-workspace/path.sh`

What this does is install the shortcuts for your desktop environment, you can also run fwtb directly from your shell.
```sh
fwtb&
```
This will print a job number, which you can `disown #[jobnum]` so that you can close your terminal.

Be careful with what you copy pasta!
